TrainingArguments:
  num_train_epochs: 1
  warmup_steps: 1
  per_device_train_batch_size: 1
  weight_decay: 0.01
  logging_steps: 1
  evaluation_strategy: epoch
  eval_steps: 10
  save_steps: 1
  gradient_accumulation_steps: 16